### ISSUE TITLE
Load time doubles on WKWebView plugin

### ISSUE THREAD

**Issue by tuomaslaa** [Telerik-Verified-Plugins/WKWebView#105]
In startup with iPhone 6 I have about 1,5s load time with Cordova/UIWebView and with WKWebView plugin it doubles to 3s. 

Will extra delay occur because of the web server bundled to the package? And will we get rid of it when Apple updates WebKit with the"file://" patch?

**Comment by EddyVerbruggen** [comment]
Hi,

Staring the webserver is a penalty indeed, depending on the device it may be shorter or longer. I haven't really timed it myself though. Once Apple releases a fix for file:// support we can use WKWebView without the webserver so indeed that will increase startup times a bit.

If you want to test whether or not the additional startup time is caused by the webserver, you can go [flip this boolean to NO](https://github.com/Telerik-Verified-Plugins/WKWebView/blob/master/src/ios/AppDelegate%2BWKWebViewPolyfill.m#L25) but your app will break ;)

Eddy
