### ISSUE TITLE
iOS 9 without local webserver

### ISSUE THREAD

**Issue by tuomaslaa** [Telerik-Verified-Plugins/WKWebView#127]
It seems that iOS 9 will support loadfileURL method so the local webserver will not be needed anymore.

**Comment by clauderic** [comment]
I personally can't even build to iOS 9 with the latest XCode 7 beta and WKWebView :/

**Comment by LukePulverenti** [comment]
It works fine here in iOS9, although I would also like to see some of the new improvements taken advantage of.

**Comment by clauderic** [comment]
The app works fine in iOS9 if it was built with XCode 6.

However, when building with XCode 7, I get an error prompting me to set disable `ENABLE_BITCODE`, otherwise it fails to build. When I do so, it builds, but the app just shows a blank screen when I run it

**Comment by nitzanwilnai** [comment]
+1 to what clauderic said. Sometimes I get a blank page, lately I have been getting a crash on Main.

**Comment by singhrajvirk** [comment]
Any luck with this? trying to use without local web server.

**Comment by EddyVerbruggen** [comment]
Hey guys, I've just release 0.5.0 which no longer uses a local webserver for iOS9. It's not really polished yet because I'm not sure if the iOS 9 final release changes things again, but at least the app should work now. When built with XCode 6.

@clauderic XCode 7 builds will still fail. I considered this a lower priority than getting this to run with iOS9 devices of course. Could you be so kind to try 0.5.0 with XCode 7 and point me at the exact thing that needs to be changed to get it to run (ENABLE_BITCODE). That may save me some time when I investigate it.

**Comment by clauderic** [comment]
@EddyVerbruggen I'm happy to report that I just built it successfully with XCode 7 beta-5 (latest) without any major hiccups. Builds now pass regardless of the value of the `Enable Bitcode` setting in Build Settings in XCode.

I did have to run `cordova platform remove ios` and `cordova platform add ios` though, otherwise builds failed when I first upgraded to 0.5.0 (even in XCode 6)

**Comment by EddyVerbruggen** [comment]
Thanks for the info!

**Comment by seb0zz** [comment]
Still had to disable Bitcode with XCode 7 beta. Also removing and readding ios platform had no effect.

**Comment by LukePulverenti** [comment]
Did anyone have to mess with the whitelist plugin for this? While I'm able to load my initial page just fine, any file:// requests for resources such as js and css fail with "Cross origin requests are only supported over HTTP"

**Comment by revolunet** [comment]
Note that using `file://` protocol with iOS 9, you cannot do local ajax calls anymore : "Cross origin requests are only supported for HTTP."

**Comment by EddyVerbruggen** [comment]
For folks wondering where bitcode can be disabled in XCode 7:

<img width="847" alt="screen shot 2015-09-10 at 10 05 51" src="https://cloud.githubusercontent.com/assets/1426370/9783271/6b789c2a-57a3-11e5-9af3-e02af0d68570.png">

**Comment by EddyVerbruggen** [comment]
@revolunet That's fixed with 0.6.0 which, ehm, uses the local webserver again.

**Comment by revolunet** [comment]
thanks @EddyVerbruggen  :)

**Comment by awebdeveloper** [comment]
@EddyVerbruggen  why did u have to use web server again

**Comment by EddyVerbruggen** [comment]
@awebdeveloper because you can't load files by xhr from the local filesystem. Even on iOS9. So f.i. Ionic template loading won't work unless the files are loaded over http.

**Comment by awebdeveloper** [comment]
so is this behavior a bug or apple don't support it

**Comment by EddyVerbruggen** [comment]
Call it what you want, but it's not supported by Apple's WKWebView.

**Comment by ffxsam** [comment]
What was the final outcome of this? I've got Xcode 7 and my device is iOS 9.2. Bitcode is disabled, and so it builds without errors, but when it deploys to my phone, it's stuck on the splash screen. I've tried 0.6.0 and 0.6.7.

**Comment by revolunet** [comment]
works here with the builtin web server
