### ISSUE TITLE
Running web server is a seperate thread

### ISSUE THREAD

**Issue by rbabayoff** [Telerik-Verified-Plugins/WKWebView#130]
Hey,

I don't know if that is already the case, but if not, should / can it be?

**Comment by tuomaslaa** [comment]
I would recommend to get rid of whole webserver because in iOS 9 there is no need for that. iOS 9 adoption rate will be very high after the launch in few weeks. iOS 8 adoption rate was little bit slower because of large download & installation size. Now iOS 9 is much more optimized and will actually save more space and can be installed on all same devices than iOS 8.

**Comment by EddyVerbruggen** [comment]
@tuomaslaa The webserver is no longer enabled when on iOS9 since the recently released 0.5.0 version of this plugin. I hope you're right about the high adoption rate but removing the webserver now would be suicide.

**Comment by EddyVerbruggen** [comment]
The webserver is here to stay since loading local files over XHR is not possible from the file:// protocol due to CORS restrictions.
