### ISSUE TITLE
Issue with landscape orientation

### ISSUE THREAD

**Issue by whitecolor** [Telerik-Verified-Plugins/WKWebView#157]
Any Ideas why app launched in landscape (on ipad 2, iOS 8.4.1) orientation take only pare of the screen, a little bit more then half width? In portrait it seem to run ok. In standard webview everyting is ok of cource.

**Comment by whitecolor** [comment]
updated to latest version ofr `cordova-plugin-wkwebview` from `npm`. It seems ok.

**Comment by bjomi** [comment]
I have this exact problem now when I updated to 0.6.0. When I use 0.4.0 this problem does not exist. So, the problem is that when I open the app i landscape a third of the screen is empty (right part of the screen). The empty part is still there when I switch to portrait.

But when I open the app in portrait from the beginning it works and I can change to landscape and everything is ok there as well.

Any ideas?

**Comment by EddyVerbruggen** [comment]
@bjomi Tried it on an iPhone 6 and couldn't reproduce it. What's your device? And which iOS?

Do you also have that behavior when creating a brand new app with the Cordova CLI, add the plugin, add the supported interface orientations, and run it? That's what I did at least.

**Comment by bjomi** [comment]
This is happening on a lot of different devices running either iOS 9.1 or iOS 8.3. As I mentioned it does not happen with 0.4.0 (haven't tried the versions in between 0.4.0 and 0.6.0).

There seems to be some issues with the view port getting the wrong size in landscape when using wkwebview. I don't know any implementation details, but this might be related:

http://stackoverflow.com/questions/30737254/wkwebview-added-as-subview-is-not-resized-on-rotation-in-swift

Some seems to have resolve the issue by triggering a scroll, but making the view scrollable and scrolling it doesn't seem to fix the issue for me:

http://stackoverflow.com/questions/28489892/wkwebview-shows-a-cropped-background-and-blank-space-after-rotation-on-ipad

Any thoughts?

**Comment by bjomi** [comment]
As I said though, the issue only occurs if I start in landscape. If I start the app when in portrait everything works as expected.

**Comment by EddyVerbruggen** [comment]
Thanks, but does it also happen on an iPhone 6, and if so, with 9.0, or did you test with 9.1 only?

Or do I need an iPhone 6+ to test starting from landscape mode..

**Comment by EddyVerbruggen** [comment]
Ah, 6+ indeed

**Comment by bjomi** [comment]
I tried on iPad Air 2 and iPad 2 and iPhone 5. All behave as described. We tested on an iPhone 6 now as well and it behaved like this:

If I start in portrait everything is fine. If I then change to landscape it keeps its width from portrait.
If I start in landscape we where able to see that it first rendered in portrait and then into landscape. When in landscape it exhibits the same artefact, the right half of the screen is white.

I don't have an iPhone six at hand, but from what I can gather the issue seems to be present on all different types of devices with both iOS 9 and iOS 8.

**Comment by bjomi** [comment]
I could always go back to 0.4.0 but that introduces other issues for us so I would very much like to see if we can find a solution here.

**Comment by EddyVerbruggen** [comment]
Me 2

**Comment by EddyVerbruggen** [comment]
So strange - the only thing remotely relevant for this issue are the changes to `ReroutingUIWebView.m`, but they don't make a difference for me.

I tried a vanilla project with the Cordova CLI which didn't show the problem, can you try that with 0.6.0 please? That will help us get closer to a solution.

Btw, do you have a `viewport` metatag in your `index.html`?

**Comment by bjomi** [comment]
Hi,

I get the exact same behaviour with a completely empty project.

**index.html**
```
<!DOCTYPE html>
<html>
    <head>
        <title>Roombler App</title>
        <link rel='stylesheet' href='bundle2.css'/>

    </head>

    <body>
    </body>
</html>
```
 **bundle2.css**
```
body {
  background-color: #000000;
}
```

**config.xml**
```
  <gap:plugin name="cordova-plugin-wkwebview" version="0.6.0" source="npm" />
  <!-- platforms -->
  <gap:platform name="ios" />
  <preference name="deployment-target" value="8.1.3" />

  <preference name='phonegap-version' value='cli-5.1.1' />

  <!-- server access -->
  <access origin="*" />
```

Regarding the viewport meta tag, yes we use that in our real project. It looks like this:
```
<meta id="viewport" name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
```

Could I give you anything else to help you track it down?

**Comment by EddyVerbruggen** [comment]
That's being built by phonegap build, isn't it (`<gap:plugin ..`)? Can you try the Cordova CLI instead?

I mean, pgb throws in a lot of sugar which I'd like to get out of the equation..

**Comment by bjomi** [comment]
Yes, its built by pgb. I don't have the Cordova CLI setup, we build
everything through pgb.

Of course I can get that sorted, but the result would probably be what you
got right? Would it be helpful if I sent you the ipa of the empty project I
built?

On Friday, September 18, 2015, Eddy Verbruggen <notifications@github.com>
wrote:

> That's being built by phonegap build, isn't it (<gap:plugin ..)? Can you
> try the Cordova CLI instead?
>
> I mean, pgb throws in a lot of sugar which I'd like to get out of the
> equation..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Telerik-Verified-Plugins/WKWebView/issues/157#issuecomment-141573012>
> .
>


-- 
*Björn Milton*, CEO & Founder

bjorn@roombler.com
Phone: +46 702 35 54 35
Twitter: @bjomi <http://twitter.com/bjomi>
Facebook: facebook.com/roombler

Strandgatan 1
621 57 Visby

**Comment by EddyVerbruggen** [comment]
Yes, email it at eddyverbruggen at gmail dot com, thx

**Comment by mhdHussein** [comment]
hi

how can i install this plugin using phonegap build and source="npm"

I need the version number 0.6.0 .. my app doesn't seem to work in IOS 9 

if you can provide me with a line to write in the config.xml file that would be great

thank you

**Comment by bjomi** [comment]
Just add:

<gap:plugin name="cordova-plugin-wkwebview" version="0.6.0" source="npm" />

to the config file

**Comment by KleggerKoder** [comment]
I'm having the same problem.  PGB too version 0.6.5 in IOS 9.  Even with user-scalable=yes in viewport zooming leaves same 1/3rd of screen white.  bjomi did you get anywhere on this?

**Comment by bjomi** [comment]
@KleggerKoder no, we didn't get anywhere unfortunately. I am experiencing the same thing with 0.6.5 as I did with 0.6.0. @EddyVerbruggen thought it had something to do with the fact that we build through Phonegap Build. Are you building through PB as well?

Another interesting fact that I cannot recall that we saw with 0.6.0 is that the screen gets the right size if you pop up the keyboard.

Anyhow, for us 0.4.0 is not exhibiting these issues, but we do miss some fixes in later versions. @EddyVerbruggen it would be great if you could publish 0.4.0 to https://www.npmjs.com/package/cordova-plugin-wkwebview. The PB repository has been deprecated so as of this week we cannot build our app with 0.4.0 anymore. Also it would be great if we could find a way to investigate this further somehow so that we could use 0.6.5.

**Comment by KleggerKoder** [comment]
@bjomi yes I'm building with PB as well, popping the keyboard does not correct the size either.

Upvote for publishing 0.4.0 to npm as I couldn't build with it to see if it corrected the problem either.  @EddyVerbruggen perhaps we should re-open or create a new issue for this?

**Comment by EddyVerbruggen** [comment]
0.4.0 is on npm now.

**Comment by bjomi** [comment]
Great, thanks!

On Tuesday, November 3, 2015, Eddy Verbruggen <notifications@github.com>
wrote:

> 0.4.0 is on npm now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Telerik-Verified-Plugins/WKWebView/issues/157#issuecomment-153285626>
> .
>


-- 
*Björn Milton*, CEO & Founder

bjorn@roombler.com
Phone: +46 702 35 54 35
Twitter: @bjomi <http://twitter.com/bjomi>
Facebook: facebook.com/roombler

Strandgatan 1
621 57 Visby

**Comment by KrisGHE** [comment]
My experiences are the same as what bjomi reported:

- Start in portrait mode = OK, then switch to landscape = OK
- Start in landscape: white bar on the right side of the screen. It looks a bit as if it takes the width of portrait mode even though it should be landscape? After switching to portrait mode the white bar remains.

- Tested with iOS 9 on an iPad2 and iPad Air 2.
- Built with Phonegap Build

Switching back to 0.4.0 fixed the problem for now.

**Comment by KleggerKoder** [comment]
@EddyVerbruggen Just a quick update I tried going back to 0.4.0 and that didn't fix the problem either.  I found that another plugin was causing the problem.  When I removed <gap:plugin name="com.phonegap.plugin.statusbar" version="1.1.0" /> from my config.xml the problem went away.
