### ISSUE TITLE
Issue when working with ios9 SDK

### ISSUE THREAD

**Issue by Sangd8** [Telerik-Verified-Plugins/WKWebView#162]
comment these code 

     This is only for iOS 9 SDK
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 90000
    [self.wkWebView loadFileURL:URL allowingReadAccessToURL:URL];
#else
        NSURLRequest* appReq = [NSURLRequest requestWithURL:URL cachePolicy:NSURLRequestUseProtocolCachePolicy timeoutInterval:20.0];
            [self.wkWebView loadRequest:appReq];
#endif

and just use function for lower SDK
  NSURLRequest* appReq = [NSURLRequest requestWithURL:URL cachePolicy:NSURLRequestUseProtocolCachePolicy timeoutInterval:20.0];
            [self.wkWebView loadRequest:appReq];

WebView can load from URL, but when run on Ios9 device, it throw me an issue on CORS.
Please help for this critical issue @EddyVerbruggen

**Comment by johnwillyn** [comment]
I am having the same problem.  After updating to latest SDK, my app fails to load.

**Comment by johnwillyn** [comment]
Further to this...I am getting this exception in my app:

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[WKWebView loadFileURL:allowingReadAccessToURL:]: unrecognized selector sent to instance 0x144608390

**Comment by EddyVerbruggen** [comment]
I need a little more info:
* which xcode version are you compiling with?
* which iOS device are your running this on?

Thx

**Comment by johnwillyn** [comment]
Xcode Version 7.0 (7A220)
iOS device iPhone 6 running iOS 8.3

**Comment by EddyVerbruggen** [comment]
Both your stacktraces refer to code which is no longer in the codebase. It was in 0.5.0, but the current 0.6.0 version fixes all these iOS9 issues.

Please update your plugin and reopen this issue if the issue resurfaces.

**Comment by johnwillyn** [comment]
OK, I just used cordova plugin commands to do the uninstall and reinstall and got version 0.5.0.  I will manually install 0.6.0 and report back what I find.

**Comment by EddyVerbruggen** [comment]
try `cordova plugin add @telerik/cordova-plugin-wkwebview`

**Comment by johnwillyn** [comment]
OK, I have my app back up and running now.  Here is what I did (with Eddy's guidance and wonderful responsiveness), and in case it helps others with the update to iOS 9 SDK.

I installed the latest plugin from git:

cordova plugin add https://github.com/Telerik-Verified-Plugins/WKWebView.git

I then did a 'cordova platform rm ios' and a 'cordova platform add ios' to remove all of the objects and pch files.

I went into xcode and turned off 'Enable Bitcode' under Build Settings; it appears to be on by default.  Otherwise, the app won't link and complains that the GCDWebServer.framework does not have bit code enabled (any suggestions for fixing this would be appreciated, but I don't think I will miss it for now).

I hope this is helpful to others.

John

**Comment by EddyVerbruggen** [comment]
Thanks for sharing that John. That bitcode thing is new in XCode7 and will disappear once the 3rd party GCDWebServer is compiled with bitcode, until then you indeed need to manually disable it in bitcode - it's in the readme btw, but who reads that neway ;)
