### ISSUE TITLE
Creates a publicly accessible webserver on the phone

### ISSUE THREAD

**Issue by morgan3d** [Telerik-Verified-Plugins/WKWebView#64]
This plugin is fantastic, but the way that it works creates a publicly accessible webserver. Anyone who knows your device's IP address and the default 12344 port can connect with a web browser and see the source for the entire app. I don't want that as a developer, and I suspect that Apple won't like it in the App store review process either.

Is it possible to make WKWebView load from the local file system directly, the way that UIWebView can, to avoid this security hole?

**Comment by EddyVerbruggen** [comment]
Excellent observation!

The embedded webserver now uses the option to bind to localhost which effectively prevents access to your apps contents from outside your phone.

Btw, loading from local filesystem is not possible with WKWebView, that's why there is an embedded webserver in the first place ;)

**Comment by daviddahl** [comment]
Is it possible for other apps to connect to your server from the phone itself?
