### ISSUE TITLE
Linker errors 

### ISSUE THREAD

**Issue by morgan3d** [Telerik-Verified-Plugins/WKWebView#65]
After the latest (excellent!) patch to restrict access to the webserver to the local device, the Cordova plugin appears to be missing some configuration that manifests at link time (after a clean build):

Undefined symbols for architecture armv7:
  "_GCDWebServerOption_Port", referenced from:
      -[AppDelegate(WKWebViewPolyfill) startServer] in AppDelegate+WKWebViewPolyfill.o
  "_OBJC_CLASS_$_GCDWebServer", referenced from:
      objc-class-ref in AppDelegate+WKWebViewPolyfill.o
  "_OBJC_CLASS_$_MyMainViewController", referenced from:
      objc-class-ref in AppDelegate+WKWebViewPolyfill.o
ld: symbol(s) not found for architecture armv7

**Comment by morgan3d** [comment]
The problem is that something in the latest patch also changed the link line, and it isn't escaping spaces. If the project name has a space in it (which is admittedly asking for trouble) the -Fdirname line will have a space and cause the linker to not find the framework. 

I believe that either escaping spaces or quoting the whole dirname will solve the problem, although maybe just a warning in the README.md is sufficient!

**Comment by EddyVerbruggen** [comment]
Hi @morgan3d that commit was [this one](https://github.com/Telerik-Verified-Plugins/WKWebView/commit/e7e7829a696fcca626e5c5dcf8b27054b5c786f0) which didn't do much more than changing 1 line of native code, so I don't think that's the root cause of your trouble.

Perhaps this is a more common plugman issue you're seeing here where reinstalling/upgrading a plugin intermittently causes this kind of trouble.
