### ISSUE TITLE
Cookie Issue

### ISSUE THREAD

**Issue by ansgarschulte** [Telerik-Verified-Plugins/WKWebView#95]
Hi,

I tried to use this plugin on my project. The app authenticate against a rest api and the first response of the api wants to store a cookie. But this cookie is not stored anymore.

Response-Header:
Set-Cookie	JSESSIONID=B799A355171A612D0D6A97E691513BB7; Path=/web.api/; HttpOnly

Any hints?

Regards Ansgar

**Comment by dburdick** [comment]
Having the same issue. This used to work with this plugin.

**Comment by axelsegers** [comment]
Same issue here JSESSIONID not stored

**Comment by tstark2** [comment]
I'm having this issue too.

**Comment by ronaldjeremy** [comment]
same issue, JSESSIONID is not being stored?

**Comment by dburdick** [comment]
From what I've observed, iOS's WkWebView simply ignores server set cookies most of the time. On occasion it will store it and send secure cookies, but generally best to avoid using this feature in your app.

**Comment by ronaldjeremy** [comment]
What, that is crazy?  This breaks so many things.  It makes it impossible to do anything at all with any webservice that uses cookies for anything!

It looks like this plugin not only doesn't work with JSESSIONID, it doesn't do anything with any cookies at all, period.  The uiwebview works just fine, as does all versions of android.  WkWebView should be tracking cookies per domain, just like the rest.

**Comment by EddyVerbruggen** [comment]
@ronaldjeremy You'd better channel your anger towards Apple because they didn't make cookie storage compatible with UIWebView. They probably had good reasons but it's a pain for us Cordova folks.

There would be a way to use cookies but I think you'd need to send your XHR requests via native code to the server so cookies can be grabbed and re-added each time. But like @dburdick said if you want to use WKWebView (via this plugin or any other) you'd best not rely on cookies.
